#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Sat Sep 19 14:25:18 2020

@author: kyle
"""

import pygame as pg



black = (0,0,0)
white = (255,255,255)

pg.init()
size = (1000,1000)
screen = pg.display.set_mode(size)
pg.display.set_caption('harry potter')
done = False
clock = pg.time.Clock()

while not done:
    for event in pg.event.get():
        if event.type == pg.QUIT:
            done =True
    screen.fill(white)   
    pg.draw.circle(screen,black, (400,400),2)
    
    
    
    pg.display.flip()
    clock.tick(60)
pg.quit()
